stages:
  generate_texts:
    cmd: >-
      poetry run python -m src.data.generate_texts
      data/raw/generated.json
      data/raw/prompt.txt
      --param_n=10
    deps:
    - src/data/generate_texts.py
    outs:
    - data/raw/generated.json
    - data/raw/prompt.txt
  parse_texts:
    cmd: >-
      poetry run python -m src.features.parse_texts
      data/raw/generated.json
      data/interim/generated.csv
    deps:
    - src/features/parse_texts.py
    - data/raw/generated.json
    outs:
    - data/interim/generated.csv
