stages:
  generate_texts:
    cmd: >-
      poetry run python -m src.data.generate_texts
      data/raw/generated.json
      data/raw/prompt.json
    deps:
    - src/data/generate_texts.py
    outs:
    - data/raw/generated.json
    - data/raw/prompt.json
